import { z } from "zod";
export const registrationValidation = z.object({
  role: z.string(),
  email: z.string(),
  password: z.string(),
  referenceNumber: z.string(),
  name: z.string().min(2, { message: "User name must be 2 character long" }),
  dateOfBirth: z.string(),
  citizenship: z.string(),
  passport: z.string(),
  travelType: z.string(),
  passportIssuDate: z.string(),
  passportExpireDate: z.string(),
  permit: z.string(),
  visaType: z.string(),
  validityVisaForm: z.string(),
  validityVisaTo: z.string(),
  numberOfEntries: z.string(),
  periodOfStay: z.string(),
  invitationParty: z.string(),
  taxPayerNumber: z.string(),
  rightToWork: z.string(),
  dateOfIssue: z.string(),
  picture: z.string(),
});
